version: '3.4'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    depends_on:
      - nginx
  nginx:
    image: ymuski/nginx-quic
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./temp/letsencrypt/:/opt/nginx/certs/
      - ./nginx.conf:/etc/nginx/nginx.conf
